name: MasterDeployCI

on: [push]

env:
  PAT: 4cb2eae651523a0a0c9fdc6c68951fb526ff3c29

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: |
          yarn && yarn build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ env.PAT }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
